name: Deploy to Docker Hub

on:
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy all images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Push to docker registry
        run: python3 Scripts/Docker.py publish