name: Test images

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test all images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: export file changes
        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Push to docker registry
        run: |
          docker version
          python3 Scripts/Docker.py build
