name: Test images

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test all images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lots0logs/gh-action-get-changed-files@2.0.6
        name: Generate a list of changed files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show a list of changed files
        run: cat ${HOME}/files.json
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Push to docker registry
        run: |
          docker version
          python3 Scripts/Docker.py build
