name: Test images

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test all images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image [base]
        if: success()
        run: |
          docker build -t ${GITHUB_REPOSITORY}:base -f Base.dockerfile .

      - name: Build image [base-debian]
        if: success()
        run: |
          docker build -t ${GITHUB_REPOSITORY}:base -f BaseDebian.dockerfile .

      - name: Build image [dotnet]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:dotnet -f Dotnet.dockerfile .

      - name: Build image [netdaemon]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:netdaemon -f Netdaemon.dockerfile .

      - name: Build image [python]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:python -f Python.dockerfile .

      - name: Build image [integration]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:integration -f Integration.dockerfile .

      - name: Build image [frontend]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:frontend -f Frontend.dockerfile .

      - name: Build image [monster]
        if: success()
        run: |
          cd Dockerfiles || exit 1
          docker build -t ${GITHUB_REPOSITORY}:frontend -f Monster.dockerfile .
