name: Update everything

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Update everything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create git config
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@users.noreply.github.com'
      - name: Update everything
        run: |
            python3 -m pip install -U requests alpinepkgs
            python3 Scripts/Update.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          reviewers: ludeeus